name: Python application

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    
    - name: Install dependencies
      run: |
        if [ -f trabajoengrupo-main/requirements.txt ]; then pip install -r trabajoengrupo-main/requirements.txt; fi
    
    - name: üîê Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHRC_PACK }}
    
    - name: üèóÔ∏è Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: ./trabajoengrupo-main
        file: ./trabajoengrupo-main/Dockerfile 
        push: true
        tags: ghcr.io/mayte256/trabajo-final:3.0.0
    
    - name: üßæ Mostrar variables b√°sicas (solo locales, no secretos)
      run: |
        echo "Probando conexi√≥n SSH con:"
        echo "Host: ${{ secrets.VPS_HOST }}"
        echo "Usuario: ${{ secrets.VPS_USER }}"
        echo "Puerto: ${{ secrets.VPS_SSH_PORT }}"
    
    - name: üß™ Probar conexi√≥n SSH
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        password: ${{ secrets.VPS_PASSWORD }}
        port: ${{ secrets.VPS_SSH_PORT }}
        script: |
          echo "‚úÖ Conexi√≥n exitosa desde GitHub Actions"
          hostname
          whoami
          uptime
    
    - name: üì¶ Copiar stack.yml to VPS (SCP)
      uses: appleboy/scp-action@v1
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        password: ${{ secrets.VPS_PASSWORD }}
        port: ${{ secrets.VPS_SSH_PORT }}
        source: "trabajoengrupo-main/stack.yml"
        target: "/home/${{ secrets.VPS_USER }}/trabajo-final/trabajoengrupo-main"
    
    - name: üöÄ Deploy to server
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        password: ${{ secrets.VPS_PASSWORD }}
        port: ${{ secrets.VPS_SSH_PORT }}
        script: |
          echo "Desplegando servicios"
          cd ~/trabajo-final/trabajoengrupo-main
          echo "Descargando la imagen desde GHCR"
          echo "${{ secrets.GHRC_PACK }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker pull ghcr.io/mayte256/trabajo-final:3.0.0
          docker tag ghcr.io/mayte256/trabajo-final:3.0.0 mayte:latest
          echo "Deteniendo los servicios (stack)"
          docker stack rm mayte || true
          echo "Esperar 10 segundos..."
          sleep 10
          echo "Desplegando el stack"
          docker stack deploy --with-registry-auth -c stack.yml mayte
          echo "üìã Verificando contenedores:"
          docker ps